### ISSUE TITLE
tracking issue for bond options

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#946]
Tracking issue for all the bond option relates issue.

 * [x] updelay and miimon: https://bugzilla.redhat.com/show_bug.cgi?id=1811605
 * [x] Properly handle conflicted bond options when mode switching.
 * [x] The query should hide bond options which does not belong to current mode.
 * [x] 'active_slave' and 'updelay': https://bugzilla.redhat.com/show_bug.cgi?id=1812786
 * [x] cannot set back 'arp_ip_target' and 'arp_interval' options to default value: https://bugzilla.redhat.com/show_bug.cgi?id=1812335

**Comment by ffmancera** [comment]
I am adding downstream bugs here.

**Comment by cathay4t** [comment]
Add issues should be fixed. Need a revisit to confirm it.

**Comment by cathay4t** [comment]
All fixed in 0.3.2
